### ISSUE TITLE
How to make gg - (go to first line) work by default

### ISSUE THREAD

**Issue by WANDEX** [I60R/page#16]
Currently pager always puts cursor approximately on the middle line of the vim window. Is this expected behavior?

Tried this and many other approaches, **how to force pager to always place cursor position on the first line by default?**
```vim
aug Pager
    au!
    au User PageOpen
        \| <cmd>call cursor(1,1)<CR>
aug END
```

**What am I doing wrong?**

Plus i don't understand how to pass commands with -e option, could you provide example?
```sh
cat | page -c NONE -e 'call cursor(1,1)'
```

**Comment by I60R** [comment]
>Is this expected behavior?

Yes, this is intentional in order to provide instant scrolling when page is opened.

There's also `scrolloff=999` option set on page buffer, so it was just possible to press j in order to move downwards. But it seems that for some reason it didn't take effect anymore (probably upstream issue, must debug it) and that's why the current behavior of placing cursor in the middle looks strange. 

>What am I doing wrong?

Nothing, this works but page moves cursor a bit later thus overrides your settings. You could replace `call cursor(1,1)` with `echom "it works"` and then call `:messages` in order to comprehend

>Plus i don't understand how to pass commands with -e option

Same as above - it works but not with cursor movements.

It's still possible to achieve the effect you want with some delay e.g. `-e 'call timer_start(500, { -> cursor(1,1) })'`

**Comment by WANDEX** [comment]
Thank you, this solution works. :muscle: 
`page -e 'call timer_start(500, { -> cursor(1,1) })'`
