### ISSUE TITLE
Setting command line options such as -u and +

### ISSUE THREAD

**Issue by jamesblau** [I60R/page#5]
First, thanks for making this! This is perfect for using a scrollback pager in kitty (https://sw.kovidgoyal.net/kitty/).

The one thing I haven't been able to figure out how to do is choose the config I'm using with page, which would let me choose which plugins to load. I'd like to set up a minimal configuration, so that it's not that much slower than less.

As far as I can tell, commands given with the -e flag are still loaded after the rest of my config.

I also get some slowness from running commands after nvim actually loads -- I'm doing "setl nonumber norelativenumber", which is different from my normal config and so the line numbers flicker on and off as page loads, and because I can't figure out how to use the "+" flag (to start at the bottom of the page) I end up using "-E 'normal G'" instead (which also flickers as the page loads at the top before jumping to the bottom). I also end up doing "set shortmess=I" in order to prevent the introduction dialogue from flashing up briefly.

In the end I'm still liking page a lot, but it ends up being noticeably slower than "command | nvim -R + -" to finish loading.

I imagine this is the sort of thing where it's a one-liner if I knew the neovim API better...

Anyway, I'll be curious if there's something I'm missing, or if this is something you think I can easily slip into page.rs somewhere.

Thanks again for the tool!

**Comment by I60R** [comment]
Hello @jamesblau, thank you for participating. 

Your suggestions was really useful. Now they are implemented in [last page version](https://github.com/I60R/page/releases/tag/v1.8.0).

It allows you to override config either with -c arg and with $XDG_CONFIG_HOME/page/init.vim file, pass custom arguments with -A="args" option, and `set shortmess+=I` is now included by default. 

Also, there's -f and -F flags that allows to start at the bottom of page. However they are shortcuts to `-E normal G`, so behavior shouldn't differ. 

But the flicker should be less noticeable in new version, since it redirects text faster.

---

Did you find any other annoyances when using page?
